### ISSUE TITLE
Addition of a flag to deactivate pvp on a region

### ISSUE THREAD

**Issue by Gorderok** [guilds-plugin/Guilds#286]
Hello, it is possible to add an option to be able to disable pvp between members of the same guild by adding a "pvp-guild" flag (for example) or to be able to at least disable it on a world so to be able to do pvp events ??
There is the option to respect the pvp flag of worldguard but it applies everywhere! I wish I could choose regions or world.

**Comment by troes1** [comment]
Also adding the option to toggle between friendlyfire would be great.

**Comment by Gorderok** [comment]
Could we have an answer?

**Comment by darbyjack** [comment]
It wouldn't be really that easy to specify it per region without doing some annoying stuff from WorldGuard. Probably a no for now.

**Comment by Gorderok** [comment]
Thank you for your answer which I hope will change because it is annoying not to be able to make pvp event even between members.

**Comment by Gorderok** [comment]
Have you found a solution since my request 1 year ago?

**Comment by darbyjack** [comment]
Hiya, so I did some research on this today and I'm at a wall and want your opinion on it. First off, yes, this is possible. But the problem we have here is that I am required to put it under a config option and the config is not loaded until the plugin is **enabled**. WorldGuard requires you to add all new flags to the system in the **onLoad()** function, which means that we can't add the flag to it in the enable method. This causes a problem because it will throw errors if they don't have worldguard / don't have it enabled in the config.

What are your thoughts on how to proceed with this?

**Comment by Gorderok** [comment]
I did not really understand, it allows to display a "pvp" flag on a region?

**Comment by Gorderok** [comment]
are you dead ?

**Comment by darbyjack** [comment]
Nope! I am alive and well!

**Comment by Gorderok** [comment]
but this will not activate pvp between members of the same guild, I do not understand

**Comment by darbyjack** [comment]
It will! In the next update, there is a permission node being implemented (`guilds.ffa`) and it will allow you to hit other members in your guild if you have it.

**Comment by darbyjack** [comment]
The guild-based fix was implemented in the latest update. The ally-based fix is still a WIP.

**Comment by Gorderok** [comment]
So if I want to activate pvp between members of the same guild, what should I do?

**Comment by darbyjack** [comment]
For guild members, for the time being, give them the permission node.

**Comment by Gorderok** [comment]
Hello, 2 years after my request for a flag, have you made any progress on the subject? because the permission works for members of the same guild but still not for allies. can you add permission to enable ally combat or worldguard flag for same guild members and allies. Thx
